sudo: required

language: python
python:
- '3.6'

install:
- curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
- pip install --default-timeout=100 git+https://github.com/jupyterhub/chartpress.git
script:
- chartpress --commit-range ${TRAVIS_COMMIT_RANGE} --tag `date +%y.%m.%d`
- git diff

deploy:
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh 
    on:
      branch: master
      tags: false
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh --tag `date +%y.%m.%d`
    on:
      branch: master
      tags: true
