language: python
python:
- '3.6'

install:
- pip install git+https://github.com/jupyterhub/chartpress.git
script:
- chartpress --commit-range ${TRAVIS_COMMIT_RANGE}

deploy:
  provider: script
  skip_cleanup: true
  script:
  - deploy.sh 
  on:
    branch:
    - master
